# Generated by Django 3.2.16 on 2022-11-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountcheckpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountcheckpoint',
            options={'ordering': ['create_date']},
        ),
        migrations.RemoveField(
            model_name='accountcheckpoint',
            name='balance',
        ),
        migrations.AddField(
            model_name='accountcheckpoint',
            name='delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='accountcheckpoint',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='accountcheckpoint',
            name='old_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='accountcheckpoint',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_ids', to='accounts.account'),
        ),
    ]
