# Generated by Django 3.2.16 on 2022-11-06 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_auto_20221106_1656'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('delta', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['end_date', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('delta', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('description', models.TextField(null=True)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_item_ids', to='accounts.account')),
                ('budget_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_item_ids', to='budgets.budget')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budgetitemcategory')),
            ],
            options={
                'ordering': ['account_id', 'category_id', 'budget_amount'],
            },
        ),
    ]
