# Generated by Django 3.2.16 on 2022-11-06 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_auto_20221106_1656'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0002_auto_20221106_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=200)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_ids', to='accounts.account')),
                ('budget_item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_ids', to='budgets.budgetitem')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
